spring.datasource.url=postgresql://authdemo_btfk_user:Uu8DkeKp2J56mbSPkrr16jIZVvnt4q0t@dpg-d89sov77f7vs73chteag-a.oregon-postgres.render.com/authdemo_btfk
spring.datasource.username=authdemo_btfk_user
spring.datasource.password=Uu8DkeKp2J56mbSPkrr16jIZVvnt4q0t

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.data-source-properties.sslmode=require

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.access.expiration=900000
jwt.refresh.expiration=604800000